// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.DAL.Queries.Original.Queries.GetCountyQuery.Search(System.String)~Synergy.Underwriting.DAL.Queries.Original.Interfaces.IGetCountyQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.DAL.Queries.Original.Queries.GetEventDelinquenciesQuery.FilterByPropertyFields(Synergy.Underwriting.DAL.Queries.Original.Models.PropertyFieldsFilterModel)~Synergy.Underwriting.DAL.Queries.Original.Interfaces.IGetEventDelinquenciesQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.DAL.Queries.Original.Queries.GetEventDelinquenciesQuery.Search(System.String)~Synergy.Underwriting.DAL.Queries.Original.Interfaces.IGetEventDelinquenciesQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.DAL.Queries.Original.Queries.GetEventDelinquenciesQuery.ApplyFilterByDelinquencyId~Synergy.Underwriting.DAL.Queries.Original.Interfaces.IGetEventDelinquenciesQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.DAL.Queries.Original.Queries.GetEventsQuery.Search(System.String)~Synergy.Underwriting.DAL.Queries.Original.Interfaces.IGetEventsQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.DAL.Queries.Original.Queries.GetEventsQuery.Search(System.String)~Synergy.Underwriting.DAL.Queries.Original.Interfaces.IGetEventsQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.DAL.Queries.Original.Queries.GetEventDelinquenciesQuery.Search(System.String)~Synergy.Underwriting.DAL.Queries.Original.Interfaces.IGetEventDelinquenciesQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.DAL.Queries.Original.Queries.GetEventDelinquenciesQuery.FilterByPropertyFields(Synergy.Underwriting.DAL.Queries.Original.Models.PropertyFieldsFilterModel)~Synergy.Underwriting.DAL.Queries.Original.Interfaces.IGetEventDelinquenciesQuery")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.DAL.Queries.Original.Queries.GetCountyQuery.Search(System.String)~Synergy.Underwriting.DAL.Queries.Original.Interfaces.IGetCountyQuery")]
