// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.Domain.BidService.GetListAsync(Synergy.Common.Domain.Models.Common.SearchArgsModel{Synergy.Underwriting.Models.Bid.BidFilterArgs,Synergy.Underwriting.Models.Bid.BidSortField},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Synergy.Common.Domain.Models.Common.SearchResultModel{Synergy.Underwriting.Models.Bid.BidModel}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.Domain.BidService.GetListAsync(Synergy.Common.Domain.Models.Common.SearchArgsModel{Synergy.Underwriting.Models.Bid.BidFilterArgs,Synergy.Underwriting.Models.Bid.BidSortField},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Synergy.Common.Domain.Models.Common.SearchResultModel{Synergy.Underwriting.Models.Bid.BidModel}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.Domain.DictionaryService.GetEventListAsync(Synergy.Common.Domain.Models.Common.SearchArgsModel{Synergy.Underwriting.Models.EventDictionaryFilterArgs,Synergy.Underwriting.Models.EventDictionarySortField},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Synergy.Common.Domain.Models.Common.SearchResultModel{Synergy.Common.Domain.Models.Common.FastEntityModel{System.Guid}}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "LINQ expressions not translated to postgressql", Scope = "member", Target = "~M:Synergy.Underwriting.Domain.DictionaryService.GetEventListAsync(Synergy.Common.Domain.Models.Common.SearchArgsModel{Synergy.Underwriting.Models.EventDictionaryFilterArgs,Synergy.Underwriting.Models.EventDictionarySortField},System.Threading.CancellationToken)~System.Threading.Tasks.Task{Synergy.Common.Domain.Models.Common.SearchResultModel{Synergy.Common.Domain.Models.Common.FastEntityModel{System.Guid}}}")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1304:Specify CultureInfo", Justification = "LINQ expressions not translated to postgressql", Scope = "type", Target = "Synergy.Underwriting.Domain.PropertyProfileService")]
[assembly: System.Diagnostics.CodeAnalysis.SuppressMessage("Globalization", "CA1307:Specify StringComparison", Justification = "LINQ expressions not translated to postgressql", Scope = "type", Target = "Synergy.Underwriting.Domain.PropertyProfileService")]
